homography_transformer:
  ros__parameters:
    # Point homography topics
    point_topic: "/goal_point"
    point_px_topic: "/point_px"
    point_marker_topic: "/goal_marker"

    # Lane homography topics
    lane_topic: "/relative_lane"
    lane_px_topic: "/lane_px"
    lane_marker_topic: "/lane_marker"