homography_transformer:
  ros__parameters:
    # Lane goal topic from detector and transformed output for follower
    point_topic: "/goal_point"
    point_output_topic: "/real_point"

    # Lane homography topics
    lane_topic: "/relative_lane"
    lane_px_topic: "/lane_px"
    lane_marker_topic: "/lane_marker"
