image_publisher:
  ros__parameters:
    subscribe_topic: "/publish_img" # Listens to Booleans to start or stop publishing images
    publish_topic: "/published_image" # Publishes the image to this topic
    publish_rate: 20
    image_path: "install/final_challenge2026/share/final_challenge2026/traffic_light_imgs/red_light_7.jpg"

yolo_detection:
  ros__parameters:
    camera_topic: "/published_image" # Subscribes to the published image topic
    traffic_light_topic: "/traffic_light" # Publishes the detected traffic light image to this topic
    publish_rate: 20

traffic_light:
  ros__parameters:
    tl_drive_topic: "/drive"
    tl_point_topic: "/tl_relative_point"
    traffic_light_topic: "/traffic_light" # Subscribes to the detected traffic light image topic

drive_publisher:
  ros__parameters:
    publish_topic: "/drive"
    subscribe_topic: "/publish_drive"
    speed: 1.0